
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: NricValidator-CI-$(Date:yy)$(DayOfYear)$(Rev:.r)

pool:
  name: 'HIP-LNX-SSP'

variables:
  buildConfiguration: 'Release'
  versionSuffix: '-alpha-$(Build.BuildNumber)'

steps:
- task: NuGetAuthenticate@1
  inputs:
    nuGetServiceConnections: 'HIP-Nexus2'
- script: dotnet restore --no-cache --configfile nuget.config
  displayName: 'Restore nuget'
- script: dotnet build fhir-codegen.sln --no-restore --configuration $(buildConfiguration) /p:VERSION_SUFFIX=$(versionSuffix) /p:GIT_VERSION=$(Build.SourceVersion)
  displayName: 'dotnet build framework $(buildConfiguration)'
- task: PublishPipelineArtifact@1
  displayName: Publish Nuget packages
  inputs:
    targetPath: '$(Build.SourcesDirectory)/packages'
    artifact: '$(Build.BuildNumber)'
    publishLocation: 'pipeline'
